version: 0.2
env:
  variables:
    FUNCTION_NAME: github-to-lambda-demo
    LAMBDA_PACKAGE: deployment-package.zip
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../$LAMBDA_PACKAGE .
      - cd ..
      - zip -g $LAMBDA_PACKAGE lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$LAMBDA_PACKAGE
      - echo FUNCTION_NAME
      - aws lambda update-function-configuration --function-name $FUNCTION_NAME --environment "Variables='$(cat variables.json)'"
      - echo "DONE!!"
